version: '2'
services:
  nginx:
    container_name: nginx
    build: 
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    command: nginx -g "daemon off";
    depends_on:
      - nodejs
      
  nodejs:
    container_name: nodejs
    build:
      context: .      
      dockerfile: Dockerfile
    image: service-cats:1.01
    expose:
      - "3000"
    command: npm start

